version: "3.8"

services:
  web:
    build: .
    env_file:
    - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: air ./cmd/main.go -b 0.0.0.0
  db:
    image : postgress:alpine
    ports:
      -5432:5432"
    volumes:
      - postgress-db:/var/lib/postgresql/data

  volumes:
    postgres-db: